baseurl = "https://bashawunitedchurch.com"
contact = "/:filename/"
languagecode = "en-us"
pluralizelisttitles = false
title = "Bashaw United Church"
[indexes]
tag = "tags"
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Events"
url = "/event"
weight = 2
[[menu.main]]
name = "Sermons"
url = "/sermon"
weight = 0
[taxonomies]
tag = "tags"
